language: php
php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer install --no-interaction --no-progress --no-suggest
  - if [[ TRAVIS_PHP_VERSION == '7.2' ]]; then curl -s -L https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar > coveralls.phar ; fi

script:
  - phpdbg -qrr vendor/phpspec/phpspec/bin/phpspec run

after_success:
  - if [[ TRAVIS_PHP_VERSION == '7.2' ]]; then php coveralls.phar -v ; fi
