name: Publish docs
on:
  push:
    branches:
    - master
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO use custom artifact name when it is supported
      - name: Build documentation archive
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: docs/docs
          artifact: webHelpDOCS2-all.zip
          docker-version: '233.14389'

      - name: Unpack documentation archive
        run: unzip ./artifacts/webHelpDOCS2-all.zip -d ./_site

      - name: Upload GitHub Pages artifact with documentation
        uses: actions/upload-pages-artifact@v3

      - name: Deploy Github Pages site with documentation
        id: deploy
        uses: actions/deploy-pages@v4
