name: Run tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            has_unique_dependencies: true
          - php: '8.2'
          - php: '8.3'
            upload_coverage: true
    container: ghcr.io/articus/phpdbg-coveralls:${{ matrix.php }}_2.7.0_2024-01-08
    steps:
      - name: Workaround for https://git-scm.com/docs/git-config/2.39.2#Documentation/git-config.txt-safedirectory
        run: chown root:root ./

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use unique composer.lock
        if: matrix.has_unique_dependencies
        run: cp ./composer.lock.${{ matrix.php }} ./composer.lock

      - name: Enable UOPZ extension
        run: phpenmod uopz

      - name: Install dependencies via Composer
        run: php ./composer.phar install --no-interaction --no-progress --prefer-dist --classmap-authoritative

      - name: Run PhpSpec tests
        run: phpdbg -qrr ./vendor/phpspec/phpspec/bin/phpspec run

      - name: Upload coverage to coveralls.io
        if: matrix.upload_coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls -v
